export const USER_SIGNUP_REQUESTED = "USER_SIGNUP_REQUESTED";
export const USER_SIGNUP_REJECTED = "USER_SIGNUP_REJECTED";
export const USER_SIGNUP_FULFILLED = "USER_SIGNUP_FULFILLED";

export const USER_SIGNIN_REQUESTED = "USER_SIGNIN_REQUESTED";
export const USER_SIGNIN_REJECTED = "USER_SIGNIN_REJECTED";
export const USER_SIGNIN_FULFILLED = "USER_SIGNIN_FULFILLED";
